// samples/solid-spa/src/components/ActivityFeed.tsx
import { For, createSignal, onCleanup, onMount } from 'solid-js';
import type { JSX } from 'solid-js';

/**
 * A real (if small) feature: a live "issue activity" feed over a WebSocket to the local API server —
 * every browser tab open on the tracker sees every other tab's issue/comment activity in real time.
 * Also exercises S7's WebSocket capture path with genuine bidirectional traffic (not a synthetic
 * ping).
 */
export default function ActivityFeed(): JSX.Element {
  const [messages, setMessages] = createSignal<string[]>([]);
  const [connected, setConnected] = createSignal(false);

  onMount(() => {
    const proto = window.location.protocol === 'https:' ? 'wss' : 'ws';
    const ws = new WebSocket(`${proto}://${window.location.host}/api/ws`);
    ws.onopen = () => setConnected(true);
    ws.onclose = () => setConnected(false);
    ws.onmessage = (event) => {
      setMessages((prev) => [...prev.slice(-19), String(event.data)]);
    };
    onCleanup(() => ws.close());
  });

  return (
    <div>
      <h4 style={{ 'margin-bottom': '4px' }}>
        Activity feed{' '}
        <span style={{ 'font-size': '11px', color: connected() ? '#16a34a' : '#dc2626' }}>
          {connected() ? 'connected' : 'disconnected'}
        </span>
      </h4>
      <ul class="activity-feed" data-testid="activity-feed">
        <For each={messages()}>{(m) => <li>{m}</li>}</For>
      </ul>
    </div>
  );
}

// samples/angular-spa/src/app/shared/activity-feed.component.ts
import { Component, OnDestroy, OnInit, signal } from '@angular/core';

/**
 * A real (if small) feature: a live "expense activity" feed over a WebSocket to the local API server —
 * every browser tab open on the app sees every create/approve/reject in real time. Also exercises S7's
 * WebSocket capture path with genuine bidirectional traffic (not a synthetic ping).
 */
@Component({
  selector: 'app-activity-feed',
  standalone: true,
  template: `
    <h4 style="margin-bottom: 4px;">
      Activity feed
      <span [style.color]="connected() ? '#16a34a' : '#dc2626'" style="font-size: 11px;">
        {{ connected() ? 'connected' : 'disconnected' }}
      </span>
    </h4>
    <ul class="activity-feed" data-testid="activity-feed">
      @for (m of messages(); track $index) {
        <li>{{ m }}</li>
      }
    </ul>
  `,
})
export class ActivityFeedComponent implements OnInit, OnDestroy {
  readonly messages = signal<string[]>([]);
  readonly connected = signal(false);
  #ws?: WebSocket;

  ngOnInit(): void {
    const proto = window.location.protocol === 'https:' ? 'wss' : 'ws';
    const ws = new WebSocket(`${proto}://${window.location.host}/api/ws`);
    this.#ws = ws;
    ws.onopen = () => this.connected.set(true);
    ws.onclose = () => this.connected.set(false);
    ws.onmessage = (event) => {
      this.messages.update((prev) => [...prev.slice(-19), String(event.data)]);
    };
  }

  ngOnDestroy(): void {
    this.#ws?.close();
  }
}
