// samples/react-spa/src/components/ThrowingWidget.tsx
import { withBugseeErrorBoundary } from '@bugsee/react';

interface Props {
  armed: boolean;
  label: string;
}

/** Throws DURING RENDER when armed — the shape `BugseeErrorBoundary`/`getDerivedStateFromError` needs to
 *  catch (an event-handler throw does NOT reach a boundary; a render throw does). */
function ThrowingWidgetImpl({ armed, label }: Props): JSX.Element {
  if (armed) {
    throw new Error(`ThrowingWidget(${label}): deliberate render-phase throw for BugseeErrorBoundary`);
  }
  return <p data-testid={`widget-ok-${label}`}>{label}: rendering fine.</p>;
}

export default ThrowingWidgetImpl;

/** The HOC form under test — its OWN local boundary + fallback, isolated from the app-level one. */
export const GuardedThrowingWidget = withBugseeErrorBoundary(ThrowingWidgetImpl, {
  fallback: (error) => (
    <p className="status-line err" data-testid="guarded-widget-fallback">
      Guarded widget caught: {error instanceof Error ? error.message : String(error)}
    </p>
  ),
  mechanism: 'uncaught',
});

// samples/solid-spa/src/components/ThrowingWidget.tsx
import { ErrorBoundary, Show } from 'solid-js';
import type { Accessor, JSX } from 'solid-js';
import { solidErrorHandler } from '@bugsee/solid';

interface Props {
  armed: Accessor<boolean>;
  label: string;
}

/**
 * Throws from a reactive computation when armed — the shape Solid's `<ErrorBoundary>` needs to catch
 * (Solid components run their body ONCE at creation; a throw has to happen inside a computation that
 * re-runs when `armed` flips, which is exactly what a dynamic JSX expression compiles to).
 */
function ThrowingWidgetImpl(props: Props): JSX.Element {
  return (
    <Show
      when={props.armed()}
      fallback={<p data-testid={`widget-ok-${props.label}`}>{props.label}: rendering fine.</p>}
    >
      {(() => {
        throw new Error(`ThrowingWidget(${props.label}): deliberate render-phase throw for ErrorBoundary`);
      })()}
    </Show>
  );
}

export default ThrowingWidgetImpl;

/** The locally-guarded form under test — its OWN `<ErrorBoundary>` + `solidErrorHandler` fallback,
 *  isolated from the app-level one. */
export function GuardedThrowingWidget(props: Props): JSX.Element {
  return (
    <ErrorBoundary
      fallback={(error) => {
        solidErrorHandler({ mechanism: 'uncaught' })(error);
        return (
          <p class="status-line err" data-testid="guarded-widget-fallback">
            Guarded widget caught: {error instanceof Error ? error.message : String(error)}
          </p>
        );
      }}
    >
      <ThrowingWidgetImpl armed={props.armed} label={props.label} />
    </ErrorBoundary>
  );
}
